### ISSUE TITLE
Betreft onduidelijkheid implementatie van method

### ISSUE THREAD

**Issue by IP14Y3RI** [gameoftrades/gameoftrades-student-kit#2]
Beste meneer Erik Hooijmeijer,

Tijdens het werken aan het project kwamen we diverse problemen tegen met het geleverde framework.
De interfaces bevatten methods waarvan het ons onduidelijk wat de bedoeling is van de implementatie van deze methode. Het voornaamste voorbeeld hiervan is de method volg van de interface Pad. 
Is het mogelijk voor u om de bijbehorende documentatie op te sturen? Wellicht dat dat onze verwarringen verheldert.

Alvast bedankt,

Met vriendelijke groet, 
Kishan, Waqar & Josh

**Comment by timvisee** [comment]
Wij, als groep, lopen tegen hetzelfde probleem aan.

Het toevoegen van JSDocs aan methods/classes, en het specificeren van de source repository in de Maven configuratie zou een mooi begin zijn.

Tim Visée

**Comment by ctrl-alt-dev** [comment]
Opmerkelijk, ik zou zweren dat ik het geheel gedocumenteerd heb.. En [inderdaad](https://github.com/gameoftrades/gameoftrades-library/blob/master/src/main/java/io/gameoftrades/model/kaart/Pad.java) :-)

```
/**
 * bepaalt op welk coordinaat je uit komt als je het pad volgt.
 * @param start het start coordinaat.
 * @return het eindpunt van het pad.
 */
Coordinaat volg(Coordinaat start);
```

Wellicht doet je IDE alsof er broncode is door de class files te decompileren. Echter de Javadoc zit er dan niet bij, daarvoor heb je de source code nodig. Het downloaden van de source code kan je met [maven of je IDE](http://stackoverflow.com/questions/2059431/get-source-jars-from-maven-repository) doen. Ook kan je de bibliotheek gewoon uitchecken van [github](https://github.com/gameoftrades/gameoftrades-library/).

### Implementatie tips

Een `Pad` is de uitkomst van het snelste pad algoritme. Afhankelijk van welk algoritme je implementeert is een bepaalde Pad implementatie handiger. Vandaar ook dat deze zelf gemaakt moet worden. 

In principe is `Pad` een wrapper rond een `Richting` array. De volg (het Pad) functionaliteit kan eenvoudig geïmplementeerd worden op basis van de `Coordinaat.naar(Richting)` methode.

De Pad implementatie wordt (deels) gecontroleerd in de `HandelaarImplTest.zouEenPadMoetenVinden()` methode.

@timvisee het specificeren van de [source repository](https://maven.apache.org/pom.html#SCM) in de Maven configuratie zegt alleen iets over de broncode van het project waar de pom een deel van uit maakt maar niets over de broncode van de gebruikte bibliotheken.
