### ISSUE TITLE
Vraag over de beweginsscores bij opdr3

### ISSUE THREAD

**Issue by David-Haile** [gameoftrades/gameoftrades-student-kit#4]
Hallo, ons groepje vroeg zich af of er een laagst te behalen score is oftewel de meest optimale tour? De laagste score is namelijk 216 in onze klas maar het lijkt alsof het steeds lager kan. We weten dat het niet per se nog beter hoeft maar toch willen we weten of er een lagere score dan 216 bij u bekend is.

**Comment by ctrl-alt-dev** [comment]
Mijn persoonlijk record is 218 - dus ik ben erg nieuwsgierig hoe jullie aan 216 gekomen zijn :-)

**Comment by David-Haile** [comment]
Oh mooi, is er een realistisch minpunt? Mijn groepje heeft namelijk tot nu toe 217, een ander groepje heeft 216, toch verwachten wij op hetzelfde punt te komen! Wij stoppen zelf bij 214 als er niet al een echt  minpunt is zodat we hier niet voor altijd door gaan.

**Comment by ctrl-alt-dev** [comment]
Allereerst, voor de uitkomst (een lijst van steden) is de score niet belangrijk. Uiteraard is de score wel van invloed op de uitkomst maar dat zie je niet direct in het resultaat. Er is voor deze opgave dan ook geen 'realistisch minpunt'.

De score tussen steden wordt bepaald door je snelste pad algoritme - als je wilt weten waar de verschillen liggen zou ik beginnen met het controleren en onderling vergelijken van de matrix van afstanden tussen steden. De uitkomsten van A\* kunnen verschillen afhankelijk van de gewichten die je hebt gebruikt. AntRace zou altijd het zelfde resultaat op op moeten leveren. 

Heb je al een unit test geschreven die de matrix bepaald en dan controleert (aan de hand van het pad) of de uitkomst juist is?
