### ISSUE TITLE
Test herkent IllegalArgumentException niet

### ISSUE THREAD

**Issue by KevinLima** [gameoftrades/gameoftrades-student-kit#6]
Code 
`if (x == 10 && y == 4){
                throw new IllegalArgumentException();
            }`

https://github.com/gameoftrades/gameoftrades-student-kit/blob/935213c8c95e96a0e256d95c1ca7576f28e4a5a7/src/test/java/io/gameoftrades/studentNN/WereldLaderImplTest.java#L96

**Comment by KevinLima** [comment]
krijgen we nog een antwoord op deze issue?

**Comment by ctrl-alt-dev** [comment]
Hoi Kevin, sorry voor de late reactie; de notificatie ervoor werd een beetje geswamped door alle andere notificaties :)

Als de test niet slaagt dan voldoe je niet aan de criteria voor de test. In dit geval dat de code een `IllegalArgumentException` moet gooien.

Ik heb even naar de code van `Team21` gekeken; jouw team toch?

In de implementatie van `WereldLaderImpl` van `Team21` zit een stuk code dat deze (en andere) inslikt; vandaar dat de test niet slaagt.
```
       } catch (IllegalArgumentException e) { e.printStackTrace();
       } catch (FileNotFoundException e){ e.printStackTrace(); 
       } catch (URISyntaxException e) { e.printStackTrace(); }
```

**Comment by KevinLima** [comment]
thanks

**Comment by atKnightSE** [comment]
Beste Kevin,

Vragen over theorie en opgaven uit het boek dan wel vragen over het A* algoritme worden kunnen tijdens de experturen worden gesteld.

Met vriendelijke groet,

E.M. van Doorn
