### ISSUE TITLE
wat wordt hiermee bedoelt 

### ISSUE THREAD

**Issue by KevinLima** [gameoftrades/gameoftrades-student-kit#7]
"Als je dit als volgt doet dan heb je bij default een DummyDebugger (die niets doet) maar kan de gebruikersinterface de GuiDebugger zetten en jij, als je dat zou willen, de AsciiArtDebugger die naar de console debug uitvoer stuurt."

**Comment by ctrl-alt-dev** [comment]
Heb je de package [io.gameoftrades.debug](https://github.com/gameoftrades/gameoftrades-library/tree/master/src/main/java/io/gameoftrades/debug) al bekeken en de Javadoc gelezen?

**Comment by atKnightSE** [comment]
Beste Erik,

Bij het praktikum ben ik niet betrokken.

Met vriendelijke groet,

E.M. van Doorn
