### ISSUE TITLE
Hoe kan de paden worden gevisualiseerd ?

### ISSUE THREAD

**Issue by KevinLima** [gameoftrades/gameoftrades-student-kit#8]
1. Is het de bedoeling dat je debugger implementeert?
2. Hoe kan ik de paden visualiseren?

**Comment by ctrl-alt-dev** [comment]
Hoi Kevin,

Nou, je hoeft zelf geen `Debugger` te implementeren, daar zijn al implementaties van. 

Als je op je algorithmen de `Debuggable` interface implementeert zoals in de documentatie staat dan ziet de `StudentUI` dat vanzelf en geeft het je een instance van `AbstractDebugPanel.GuiDebugger`.
(Daarnaast zijn er ook de `AsciiArtDebugger` voor op de console en de `DummyDebugger` die niets doet).

Als je dan vervolgens van uit je algorithme `debugger.debugPad(..)` aanroept toont de `StudentUI` je pad als een stap.
