### ISSUE TITLE
Coördinaten op de kaart

### ISSUE THREAD

**Issue by kadmosb1** [gameoftrades/gameoftrades-student-kit#9]
Goedemorgen,

Ik heb even gekeken naar de tests en heb een probleem ondervonden in de zouStadMetVerkeerdeCoordinatenNietMoetenLaden test. In deze test zou een IllegalArgumentException moeten worden gegooid omdat (volgens de test) de locatie 0,0 niet valide is voor een stad. Volgens de opdracht zijn de steden opgeschreven met x en y coordinaten ("De stedenlijst voor deze wereld is (x/y coördinaat, naam stad)") en is het coordinaat 0,0 linksboven ("Het coordinaat 0,0 is linksboven"). Het coordinaat 0,0 zou dus volgens de OPDRACHT.md valide moeten zijn, alleen volgens de test niet.

Zit er een fout in de test of in de OPDRACHT.md?

Met vriendelijke groet,
Theodoor Paganoni

**Comment by ctrl-alt-dev** [comment]
Beste Theodoor,

Heb je de [Voorbeeld Terreinkaart](https://github.com/gameoftrades/gameoftrades-student-kit/blob/master/OPDRACHT.md#voorbeeld-terreinkaart) al aandachtig bestudeerd? :-)

Met vriendelijke groet,
Erik Hooijmeijer

**Comment by ctrl-alt-dev** [comment]
Ach :) De tip `Het coordinaat 0,0 is linksboven.` klopt niet. Dat moet 1,1 zijn.

**Comment by kadmosb1** [comment]
Top. Dank je, Erik.
